version: v1
plugins:
  - name: openapiv2
    out: .
    opt:
      - logtostderr=true
      - allow_merge=true
      - json_names_for_fields=false
      - openapi_naming_strategy=fqn
      - simple_operation_ids=true
      - Mgoogle/protobuf/any.proto=github.com/cosmos/cosmos-sdk/codec/types
      - Mcosmos/orm/v1/orm.proto=cosmossdk.io/orm

