version: v1
plugins:
  - name: swagger
    out: .
    opt:
      - logtostderr=true
      - allow_merge=true
      - json_names_for_fields=false
      - openapi_naming_strategy=fqn
      - simple_operation_ids=true
